### ISSUE TITLE
Frosty freezing (lol) and then crashing

### ISSUE THREAD

**Issue by JorgenaBudgie** [marv7000/AssetBankPlugin#2]
Whenever I use the export button "AntStateAsset," Frosty stops responding. I'm trying to export from BF4.

Log error:
`Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index

   at System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource)
   at System.Collections.Generic.List`1.get_Item(Int32 index)
   at AssetBankPlugin.Export.AnimationExporterSEANIM.Export(InternalAnimation animation, InternalSkeleton skeleton, String path)
   at AssetBankPlugin.AntStateAssetDefinition.Export(EbxAssetEntry entry, String path, String filterType)
   at FrostyEditor.MainWindow.contextMenuExportEbx_Click(Object sender, RoutedEventArgs e) in C:\Users\name\Downloads\FrostyToolsuite-1.0.6.3\FrostyToolsuite-1.0.6.3\FrostyEditor\Windows\MainWindow.xaml.cs:line 1078
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.Controls.MenuItem.InvokeClickAfterRender(Object arg)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)`

**Comment by marv7000** [comment]
Hi, which asset are you exporting specifically? Also, did you set a Skeleton in the plugin settings?

**Comment by zuhn0x** [comment]
HOW DO I USE THIS PLUGIN WHERES DLL FILE FOR IT

**Comment by marv7000** [comment]
you need to build it yourself
